//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comercio2
    {
        public int Id { get; set; }
        public decimal lat { get; set; }
        public decimal lng { get; set; }
    }
}
