//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPedidos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabasePedidosOnlineEntities : DbContext
    {
        public DatabasePedidosOnlineEntities()
            : base("name=DatabasePedidosOnlineEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<comercio> comercio { get; set; }
        public virtual DbSet<Menu> Menu { get; set; }
        public virtual DbSet<pedido> pedido { get; set; }
        public virtual DbSet<Table> Table { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
