//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoPedidos
{
    using System;
    using System.Collections.Generic;
    
    public partial class pedido
    {
        public int IdPedido { get; set; }
        public string IdTipoPedido { get; set; }
        public Nullable<int> IdCombo { get; set; }
        public Nullable<int> IdUsuario { get; set; }
        public string IdComercio { get; set; }
    }
}
